function writeRinex302Obs_GPS_L1CA(filename, meta, epochs)
% Write RINEX 3.02 observation file (GPS only): C1C L1C D1C S1C
% epochs(k): .week .sow .sat{n} .C1C(n) .L1C(n) .D1C(n) .S1C(n)

% ===== Guard: no epochs -> do not write file =====
if isempty(epochs)
    warning('RINEX OBS not written: no valid observation epochs were generated.');
    return;
end

fid = fopen(filename,'w');
if fid < 0
    error('Cannot open %s for writing.', filename);
end

% -------- Header (80-char lines) --------
% Use fixed columns: data in cols 1-60, label in cols 61-80
hline = @(data,label) w80(fid, sprintf('%-60s%-20s', data, label));

% RINEX VERSION / TYPE
hline(sprintf('%9.2f%-11s%-20s%-20s', 3.02, '', 'OBSERVATION DATA', 'G: GPS'), ...
      'RINEX VERSION / TYPE');

% PGM / RUN BY / DATE
pgm   = 'MATLAB';
runby = 'SoftSim';
dt    = datestr(now, 'dd-mmm-yy HH:MM');
hline(sprintf('%-20s%-20s%-20s', pgm, runby, [dt ' ']), ...
      'PGM / RUN BY / DATE');

% COMMENT (optional)
hline('Generated by SoftSim (GPS L1 C/A only)', 'COMMENT');

% MARKER NAME / NUMBER
hline(padN(getField(meta,'markerName',''),60),   'MARKER NAME');
hline(padN(getField(meta,'markerNumber',''),60), 'MARKER NUMBER');

% OBSERVER / AGENCY (better split; if you only have observerAgency, keep it as observer)
observer = getField(meta,'observer','');
agency   = getField(meta,'agency','');
if isempty(observer) && isempty(agency)
    observer = getField(meta,'observerAgency','');
end
hline(sprintf('%-20s%-40s', padN(observer,20), padN(agency,40)), 'OBSERVER / AGENCY');

% REC # / TYPE / VERS  (serial / type / version)
recNum  = getField(meta,'receiverNumber','');
recType = getField(meta,'receiverType','');
recVer  = getField(meta,'receiverVersion','');
hline(sprintf('%-20s%-20s%-20s', padN(recNum,20), padN(recType,20), padN(recVer,20)), ...
      'REC # / TYPE / VERS');

% ANT # / TYPE (serial / type)
antNum  = getField(meta,'antennaNumber','');
antType = getField(meta,'antennaType','');
hline(sprintf('%-20s%-20s%-20s', padN(antNum,20), padN(antType,20), ''), ...
      'ANT # / TYPE');

% APPROX POSITION XYZ
xyz = getField(meta,'approxPosXYZ',[0 0 0]);
if numel(xyz) ~= 3, xyz = [0 0 0]; end
hline(sprintf('%14.4f%14.4f%14.4f', xyz(1), xyz(2), xyz(3)), 'APPROX POSITION XYZ');

% ===== MUST for strict tools: ANTENNA: DELTA H/E/N =====
% If unknown, set [0 0 0] (meters)
dHEN = getField(meta,'antDeltaHEN',[0 0 0]);   % [H E N]
if numel(dHEN) ~= 3, dHEN = [0 0 0]; end
hline(sprintf('%14.4f%14.4f%14.4f', dHEN(1), dHEN(2), dHEN(3)), 'ANTENNA: DELTA H/E/N');

% SYS / # / OBS TYPES (GPS only)
hline(sprintf('G%5d %-3s %-3s %-3s %-3s', 4, 'C1C','L1C','D1C','S1C'), ...
      'SYS / # / OBS TYPES');

% INTERVAL
hline(sprintf('%10.3f', getField(meta,'interval',1.0)), 'INTERVAL');

% (optional but recommended) receiver clock offsets applied?
% 0 = not applied, 1 = applied
rcvClk = getField(meta,'rcvClockOffsAppl',0);
hline(sprintf('%6d', rcvClk), 'RCV CLOCK OFFS APPL');

% TIME OF FIRST OBS / TIME OF LAST OBS
tsys = upper(strtrim(getField(meta,'timeSystem','GPS')));
if isempty(tsys), tsys = 'GPS'; end
tsys = padN(tsys,3);

[y,mo,d,hh,mm,ss] = GPST2Cal(epochs(1).week, epochs(1).sow);
% Put time system in a stable column region (more standard than %8s)
hline(sprintf('%6d%6d%6d%6d%6d%13.7f     %3s', y,mo,d,hh,mm,ss, tsys), ...
      'TIME OF FIRST OBS');

[y,mo,d,hh,mm,ss] = GPST2Cal(epochs(end).week, epochs(end).sow);
hline(sprintf('%6d%6d%6d%6d%6d%13.7f     %3s', y,mo,d,hh,mm,ss, tsys), ...
      'TIME OF LAST OBS');

% LEAP SECONDS  (FIX: remove nested sprintf bug)
leaps = getField(meta,'leapSeconds',0);
hline(sprintf('%6d', leaps), 'LEAP SECONDS');

% SIGNAL STRENGTH UNIT
hline('DBHZ', 'SIGNAL STRENGTH UNIT');

% END OF HEADER
hline('', 'END OF HEADER');

% -------- Data --------
for k = 1:numel(epochs)
    [y,mo,d,hh,mm,ss] = GPST2Cal(epochs(k).week, epochs(k).sow);
    nsat = numel(epochs(k).sat);

    % Epoch record: flag=0, nsat
    fprintf(fid, '> %4d %02d %02d %02d %02d %11.7f %1d%3d\n', ...
        y, mo, d, hh, mm, ss, 0, nsat);

    for i = 1:nsat
        prn = epochs(k).sat{i};
        % Ensure 3-char PRN like 'G02'
        if numel(prn) == 2
            prn = ['G0' prn(2)];
        end
        fprintf(fid, '%3s', prn);

        writeObsField(fid, epochs(k).C1C(i));
        writeObsField(fid, epochs(k).L1C(i));
        writeObsField(fid, epochs(k).D1C(i));
        writeObsField(fid, epochs(k).S1C(i));

        fprintf(fid, '\n');
    end
end

fclose(fid);
end

% ---- helpers ----
function w80(fid, s)
if length(s) < 80
    s = [s repmat(' ',1,80-length(s))];
else
    s = s(1:80);
end
fprintf(fid, '%s\n', s);
end

function s = padN(x, n)
x = char(x);
x = strtrim(x);
if length(x) > n
    x = x(1:n);
end
s = [x repmat(' ',1,n-length(x))];
end

function out = getField(st, name, defaultVal)
if isstruct(st) && isfield(st, name) && ~isempty(st.(name))
    out = st.(name);
else
    out = defaultVal;
end
end

function writeObsField(fid, val)
% Field: value(14) + LLI(1) + SSI(1). We set LLI/SSI = 0.
% RINEX 3 OBS field width is 16 chars per observation.
if isnan(val)
    fprintf(fid, '%16s', '');
else
    fprintf(fid, '%14.3f%1d%1d', val, 0, 0);
end
end
